### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by metya** [xintrea/LoLoSwitcher#12]
Поставил, в конфиге указал нужный инпут. 

В тестах все хорошо. 

Но при печати не переключает автоматически раскладку. 

Когда же руками через шифт переключаешь то вылетает с segmentation fault.

**Comment by xintrea** [comment]
Вы не дали никакой информации.

Какой дистрибутив Linux? Какая битность? Каким компилятором собирали?

> Но при печати не переключает автоматически раскладку.

Вы точно ничего не путаете? LoLo Switcher - это переключатель раскладки по заданным клавишам, и все. Никакой автоматической переключения раскладки в нем нет.

> Когда же руками через шифт переключаешь то вылетает с segmentation fault.

Тут только запускать loloswitcher под GDB, и показывать backtrace вывод после сегфолта. И показывать значения переменных и параметров.

**Comment by metya** [comment]
Простите, ишью скорее была затравочкой к обсуждению. Так как не знал, жив ли проект. 

Про дистрибутив. 
```
Linux metya 5.6.12-1-MANJARO #1 SMP PREEMPT Sun May 10 14:36:43 UTC 2020 x86_64 GNU/Linux
```

соответственно cmake и make стандартные из дистрибутива. 

```
cmake version 3.17.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

```
GNU Make 4.3
Эта программа собрана для x86_64-pc-linux-gnu
```

Про смену раскладки, 
соррян, кажется я тогда не понял. Я думал, почему то, что loloswitcher умеет менять раскладку уже написанного слова. Или просто смена раскладки по шифтам и ничего больше?

**Comment by xintrea** [comment]
На официальной странице написано:

> Принцип работы
> LoLo Switcher работает как процесс на низком системном уровне, и получает данные от клавиатуры напрямую из файла устройства. Обнаружив нужную последовательность кодов, LLS вызывает функции X11, отвечающие за переключение раскладки.

https://webhamster.ru/site/page/index/articles/projectcode/180

И еще подробнее тут: https://webhamster.ru/site/page/index/articles/projectcode/181

**Comment by metya** [comment]
Все понял. Прошу прощения, что ввел себя в заблуждение)
