### ISSUE TITLE
X11?

### ISSUE THREAD

**Issue by Shura0** [xintrea/LoLoSwitcher#3]
Не проблема, просто памятка. Не знаю, кто тут виноват, но отследить нажатие клавиш "Ctrl+V" и "Shift+Ins" невозможно, наверное X11 блокирует

**Comment by xintrea** [comment]
1. Для начала покажите вывод команды:

/sbin/loloswitcher -t3

2. Вы собрались переключать язык по клавише Ctrl+V? Вы ничего не путаете?

3. Вы собрались переключать язык по клавише Shift+Ins?? Вы точно ничего не путаете?

**Comment by Shura0** [comment]
```
shura [/home/shura/projects/LoLoSwitcher]$ build/loloswitcher -t3
Read config test.

-------------------
Reading config data from file /home/shura/.config/loloswitcher/config.ini
-------------------
InputDevice: /dev/input/by-path/platform-i8042-serio-0-event-kbd
DeviceType: 0
NumberOfLayout: 2
SwitchMethod: 0
EventFilter: ^1,[0-9]+,[0-9]+;$
Sequence0: (1,29,1;|1,29,2;)1,110,1;1,110,0;$
Sequence1: (1,42,1;|1,42,2;)1,110,1;1,110,0;$
Command0: /home/shura/projects/LoLoSwitcher/xclip_helper.pl -a
Command1: /home/shura/projects/LoLoSwitcher/xclip_helper.pl
```
Хотел приспособить программу не для переключения раскладок, а для буфера обмена. Хотел сделать так, чтобы можно было копировать подряд несколько кусков текста и потом также подряд вставлять. Для этого надо ловить событие вставки, чтобы после него программно загонять в буфер следующий скопированный кусок. Оказалось, что событие вставки нельзя таким образом промониторить, хотя с опцией -t1 всё работает нормально, клавиши отображаются.
