### ISSUE TITLE
приколы с инсталяцией

### ISSUE THREAD

**Issue by ghost** [xintrea/LoLoSwitcher#4]
1.
_влепил я строку 
`/usr/sbin/loloswitcher`
в `.profile` и загрузка mint 19 в GUI зависает на чёрном экране... наверное я чего-то не так делаю._

P.S. Оказывается в GUI есть "Центр управления", в котором есть "Параметры запускаемых приложений" и туда можно добавить этот вызов, и всё работает ) 
P.P.S. и надо выполнить `sudo chmod u+s /usr/sbin/loloswitcher` . вроде в CMakeLists.txt это есть, и вначале работало. но потом перестало работать на автозагрузке, и пришлось ещё раз назначить эти флаги... (я не понимать)

2.
_список моих устройств был такой:_
```
user@pc:/dev/input/by-id$ ls
usb-03ee_8801-event-if01          usb-COMPANY_USB_Device-if01-event-mouse
usb-03ee_8801-event-kbd           usb-COMPANY_USB_Device-if01-mouse
usb-COMPANY_USB_Device-event-kbd  usb-COMPANY_USB_Device-if02-event-kbd
```

_kbd которые с натуральным именем "`COMPANY_USB_Device`" (также называется в винде) не бросали спец коды, а простые буквы гнали, и на одиночный шифт и контрол не реагировали.

а то устройство, что с жуткими кодами в имени -- заработало.
заработало `/dev/input/by-id/usb-03ee_8801-event-kbd`_
3. 
_привык я к контролам :_ 
```
Sequence0=(?<!1,42,1;|1,42,2;|1,97,1;|1,97,2;|1,56,1;|1,56,2;|1,100,1;|1,100,2;)1,29,1;1,29,0;$
Sequence1=(?<!1,29,1;|1,29,2;|1,54,1;|1,54,0;|1,56,1;|1,56,2;|1,100,1;|1,100,2;)1,97,1;1,97,0;$
```
_но заметил, что у вас в скобочках была пара не 
`1,97,1;    1,97,0;`
а почему то
`1,97,1;    1,97,2;`
это получается у вас правый контрол не такой, как у меня?_
4.
_в общем из консольки если запускать , то теперь всё работает!
круто !
ведь эта проблема линкуксов была практически всегда!
**спасибо** вам, и надеюсь метод попрёт в релизы._

**Comment by xintrea** [comment]
> но заметил, что у вас в скобочках была пара не
> 1,97,1; 1,97,0;
> а почему то
> 1,97,1; 1,97,2;
> это получается у вас правый контрол не такой, как у меня?

В скобочках где? В дефолтном конфиге при установке LoLoSwitcher? В статье о конфигурировании LoLoSwitcher https://webhamster.ru/site/page/index/articles/projectcode/181 ?

**Comment by xintrea** [comment]
Кстати, немногие знают, но можно запускать несколько экземпляров LoLoSwitcher одновременно. Они друг другу не мешают. Для этого нужно только, чтобы бинарник и найстройки были в одном каталоге. 

Тогда появляется возможность иметь несколько альтернативных настроек поведения программы, причем они работают параллельно.
