### ISSUE TITLE
Нажатие клавиши считывает, но язык не переключается

### ISSUE THREAD

**Issue by kirsanov-anton-info** [xintrea/LoLoSwitcher#5]
Здравствуйте, такая проблема, есть в консоли писать "loloswitcher", программа запускается, но язык не переключается. Если написать "loloswitcher -t1", то программа реагирует на нажитие/удержание клавиш. Если "loloswitcher -t2", то программа пишет:

Language layout test.
Layout found:
0 - English (Macintosh) (Active)
1 - Russian (Macintosh) 
2 - English (US)

Клавиатура от Apple не влияет, пробовал другие, проблема та же.

Если "loloswitcher -t3":
Read config test.

Reading config data from file /home/OREN/anton.dorozhko/.config/loloswitcher/config.ini

InputDevice: /dev/input/by-path/pci-0000:00:14.0-usb-0:5.2:1.0-event-kbd
DeviceType: 0
NumberOfLayout: 2
SwitchMethod: 1
EventFilter: ^1,[0-9]+,[0-9]+;$
Sequence0: (?<!1,29,1;|1,29,2;|1,97,1;|1,97,2;|1,56,1;|1,56,2;|1,100,1;|1,100,2;)1,42,1;1,42,0;$
Sequence1: (?<!1,29,1;|1,29,2;|1,97,1;|1,97,2;|1,56,1;|1,56,2;|1,100,1;|1,100,2;)1,54,1;1,54,0;$
Command0: beep -f 440 -l 25
Command1: beep -f 520 -l 25

Пробовал забиндить другие клавиши, не работает. Кто знает, чем помочь?
Через GNOME Tweak Tool тоже не получается забиндить так, чтобы одна клавиша всегда включала конкретный язык.

**Comment by xintrea** [comment]
> Если написать "loloswitcher -t1", то программа реагирует на нажатие/удержание клавиш.

Что показывает эта команда? Просто нажимаемые символы или коды этих символов?

**Comment by ddemydenko** [comment]
Можно назначить переключение на команду
Command0=gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval "imports.ui.status.keyboard.getInputSourceManager().inputSources[0].activate()"
Эта команда включает первую раскладку клавиатуры. Соответвенно inputSources[1] вторую и inputSources[2] терью

Таким образом можно забиндить три языка

```
Command0=gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval "imports.ui.status.keyboard.getInputSourceManager().inputSources[0].activate()"
Command1=gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval "imports.ui.status.keyboard.getInputSourceManager().inputSources[1].activate()"
Command2=gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval "imports.ui.status.keyboard.getInputSourceManager().inputSources[2].activate()"
```

**Comment by xintrea** [comment]
> Можно назначить переключение на команду
> Command0=gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval "imports.ui.status.keyboard.getInputSourceManager().inputSources[0].activate()"
> Эта команда включает первую раскладку клавиатуры. Соответвенно inputSources[1] вторую и inputSources[2] терью
> 
> Таким образом можно забиндить три языка

У него в системе три языка, а в конфиге LoLo Switcher прописана настройка двух (параметр NumberOfLayout). Для трех языков, естественно, в нем надо прописывать значение 3.
