### ISSUE TITLE
The USB keyboard is lost after replugging

### ISSUE THREAD

**Issue by bodqhrohro** [xintrea/LoLoSwitcher#6]
The keyboard appers with the same name in `/dev/input/by-id/`, but LoLoSwitcher no more receives events from it, so I have to restart it manually.

This probably can be automated via a udev rule, though it would be better if LoLoSwitcher handled it itself.

**Comment by xintrea** [comment]
Yes, i known about this problem. If I find time, I will fix it. So far, I consider this problem uncritical.

**Comment by xintrea** [comment]
It is fixed at commit:

https://github.com/xintrea/LoLoSwitcher/commit/0aae6fd4ad111b6f56eb84d357bc62e83da57ae8

Thanks!
