### ISSUE TITLE
Вылетает при первом переключении раскладки

### ISSUE THREAD

**Issue by alexgeirby** [xintrea/LoLoSwitcher#7]
gcc 9.2.0, Arch Linux
Программа вылетает c Segmentation fault на memset в KeyLayout::getLayouts при переключении раскладки, если собирать с оптимизацией. Собранная с -O0 не вылетает.
Если исправить предупреждение компилятора об отсутствии возвращаемого значения у KeyLayout::setActiveGroup (добавив в конец return 0) вылетать перестаёт. На другой системе с gcc 4.7.1 такой хохмы не было.

**Comment by xintrea** [comment]
Исправлено в релизе LoLoSwitcher v.0.30

https://github.com/xintrea/LoLoSwitcher/releases/tag/v.0.30
